### ISSUE TITLE
请求《十万个为什么》和《青年自学丛书》

### ISSUE THREAD

**Issue by moe-rika** [ProletRevDicta/Prolet#1805]
上海人民出版社

**Comment by hubred-rev** [comment]
https://github.com/hubred-rev/Prolet

**Comment by moe-rika** [comment]
@ProletRevDicta request for pin

**Comment by moe-rika** [comment]
十万个为什么
https://github.com/hubred-rev/Prolet/tree/master/%E5%8D%81%E8%90%AC%E5%80%8B%E7%82%BA%E4%BB%80%E9%BA%BC

青年自学丛书

https://github.com/hubred-rev/Prolet/tree/master/%E8%87%AA%E5%AD%B8%E5%8F%A2%E6%9B%B8

**Comment by moe-rika** [comment]
@ProletRevDicta 请求unpin

**Comment by moe-rika** [comment]
https://github.com/ProletRevDicta/Prolet/issues/2704
