### ISSUE TITLE
I lost my mail password since the last message.

### ISSUE THREAD

**Issue by qt4-re** [ProletRevDicta/Prolet#19]
Please contact: funlland@protonmail.com

**Comment by qt4-re** [comment]
### 彻底批判唯自由软件论
唯自由软件论是鄙人和PAPER之间爆发的一次意识形态冲突，我对你们轻视GitHub的思想表示极端反对。
1.我使用人工智能，如果分享更多的源信息，源信息是有log信息的，通过log信息必然可以直接锁定我的帐号。
2.百度云要用支付宝等支付、百度帐号要绑定手机，也就是间接的实名认证。
3.我身处五线城市、并且相邻一线城市，并且在线下-线上冲塔。
4.此城市没有多少人使用自由软件。
**结论：如果没有群众性的自由软件运动，它们可以很轻易地嗅探、搜集此城市使用自由软件时产生的流量，唯自由软件论是浪费阶级力量的反动理论，对本地工运不会带来丝毫帮助。**
我不管你们对我有什么意见，反正我就是懒得太过关心自由软件、甚至歌功颂德地写起了它们的代码。

**Comment by qt4-re** [comment]
**5.审核、广告已经开始调戏我了**

**Comment by qt4-re** [comment]
我就是队内最大的小资产阶级知识分子

**Comment by DiazoPlus** [comment]
记得GitHub也是个实名制的地方就好了。

**Comment by qt4-re** [comment]
> 记得GitHub也是个实名制的地方就好了。

我已经把比特币资金支付渠道弄好了。

**Comment by qt4-re** [comment]
所有源信息已清除log_id，代码：
`import os;wr='webcam recognize'`
`for a,b,c in os.walk(wr):`
`    for d in c:`
`        print(d)`
`        f=open('/'.join([wr,d]),'rb');i=eval(f.read());f.close()`
`        if 'log_id'in i:del i['log_id']`
`        f=open('/'.join([wr,d]),'w+');f.write(repr(i));f.close()`
